### ISSUE TITLE
Crash while rendering tile entity. 

### ISSUE THREAD

**Issue by iChun** [iChun/IssueTracker-PortalGun#23]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/11/13 12:26 AM
Description: Rendering Tile Entity

java.lang.NullPointerException
at portalgun.client.render.TileRendererPortalMod.func_76894_a(TileRendererPortalMod.java:211)
at net.minecraft.client.renderer.tileentity.TileEntityRenderer.func_76949_a(SourceFile:106)
at net.minecraft.client.renderer.tileentity.TileEntityRenderer.func_76950_a(SourceFile:98)
at net.minecraft.client.renderer.RenderGlobal.func_72713_a(RenderGlobal.java:597)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1505)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1115)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
at net.minecraft.client.main.Main.main(SourceFile:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by alpharulesirulee** [comment]
portal gun is the problem
at portalgun.client.render.TileRendererPortalMod.func_76894_a(TileRendererPortalMod.java:211)

by the way post the full log
