### ISSUE TITLE
Major rendering issues.

### ISSUE THREAD

**Issue by modmuss50** [iChun/IssueTracker-PortalGun#67]
![java_2017-10-02_11-51-57](https://user-images.githubusercontent.com/4324090/31074371-3bd75e5e-a768-11e7-88e9-e7214de02b9b.png)

```
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: java.lang.RuntimeException: Error creating shader: Fragment shader failed to compile with the following errors:
ERROR: 0:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: error(#273) 1 compilation errors.  No code generated


[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.ichunutil.client.render.ShaderHelper.createShader(ShaderHelper.java:148)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.ichunutil.client.render.ShaderHelper.createProgram(ShaderHelper.java:90)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.portalgun.client.render.TileEntityRendererPortalMaster.drawFrontShader(TileEntityRendererPortalMaster.java:330)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.portalgun.client.render.TileEntityRendererPortalMaster.drawPortalBorderAndOutline(TileEntityRendererPortalMaster.java:199)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.portalgun.client.render.TileEntityRendererPortalMaster.render(TileEntityRendererPortalMaster.java:141)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.portalgun.client.render.TileEntityRendererPortalMaster.render(TileEntityRendererPortalMaster.java:37)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:161)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:133)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:732)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1398)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1312)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1115)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1207)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.main.Main.main(Main.java:118)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[11:51:40] [main/INFO]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at GradleStart.main(GradleStart.java:26)
[11:51:40] [main/ERROR]: Error: No shaders attached to current program 
```

iChunUtil-1.12.2-7.0.0.jar
PortalGun-1.12.2-7.0.0.jar

AMD R9 270x GPU
Windows 10

**Comment by modmuss50** [comment]
Just found the other issue about it: https://github.com/iChun/IssueTracker-Mods/issues/87
